---
name: Docker Build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - '.github/workflows/call-docker-build.yaml'
      - 'docker-entrypoint.sh'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/call-docker-build.yaml'
      - 'docker-entrypoint.sh'
  workflow_dispatch:
  repository_dispatch:
  schedule:
    # re-run montly to keep image fresh with upstream base images
    - cron: '0 12 15 * *'

jobs:

  build-jekyll-image:

    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    name: Call Docker Build Jekyll

    # my fork of bretfisher/docker-build-workflow
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main

    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    
    with:
      cancel-previous-runs: true
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/jekyll
      platforms: linux/amd64,linux/arm64
      target: jekyll

  build-jekyll-serve-image:

    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    name: Call Docker Build Jekyll-Serve

    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main

    needs: build-jekyll-image

    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event_name == 'schedule'

    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    
    with:
      cancel-previous-runs: false
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/jekyll-serve
      platforms: linux/amd64,linux/arm64
      target: jekyll-serve
